# Site settings
title: "Code Grump"
email: maddogmcclure@gmail.com
description: Track the Code Grump's journey through all things Development.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://localhost:4000" # the base hostname & protocol for your site
github_username:  alexBraidwood

# Build settings
markdown: kramdown
permalink: /articles/:title
